# Generated by Django 6.0.3 on 2026-04-15 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('clinical_exam', models.TextField(blank=True, verbose_name='Examen clinique')),
                ('diagnosis', models.TextField(verbose_name='Diagnostic')),
                ('treatment', models.TextField(blank=True, verbose_name='Traitement prescrit')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Date suivi')),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.appointment', verbose_name='RDV')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='staff.doctor', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('type', models.CharField(choices=[('BLOOD', 'Analyse sanguine'), ('URINE', 'Analyse urinaire'), ('XRAY', 'Radiographie'), ('ECHO', 'Échographie'), ('SCAN', 'Scanner'), ('MRI', 'IRM'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description / Examens demandés')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('DONE', 'Réalisé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=15, verbose_name='Statut')),
                ('result', models.TextField(blank=True, verbose_name='Résultats')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/', verbose_name='Fichier résultat')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='consultations.consultation', verbose_name='Consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': "Demande d'examen",
                'verbose_name_plural': "Demandes d'examens",
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Instructions générales')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation', verbose_name='Consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='staff.doctor', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Ordonnance',
                'verbose_name_plural': 'Ordonnances',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200, verbose_name='Médicament')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('frequency', models.CharField(max_length=100, verbose_name='Fréquence')),
                ('duration', models.CharField(max_length=100, verbose_name='Durée')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.prescription', verbose_name='Ordonnance')),
            ],
            options={
                'verbose_name': "Ligne d'ordonnance",
            },
        ),
    ]
