# Generated by Django 6.0.3 on 2026-03-18 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('OTHER', 'Autre')], max_length=10)),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf/Veuve')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patients/photos/')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('phone_alt', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('insurance_name', models.CharField(blank=True, max_length=100, verbose_name='Assurance')),
                ('insurance_number', models.CharField(blank=True, max_length=50)),
                ('file_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Dossier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('chronic_diseases', models.TextField(blank=True, verbose_name='Maladies chroniques')),
                ('past_surgeries', models.TextField(blank=True, verbose_name='Antécédents chirurgicaux')),
                ('family_history', models.TextField(blank=True, verbose_name='Antécédents familiaux')),
                ('current_medications', models.TextField(blank=True, verbose_name='Médicaments en cours')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Dossier médical',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_pressure_sys', models.IntegerField(blank=True, null=True, verbose_name='Tension sys.')),
                ('blood_pressure_dia', models.IntegerField(blank=True, null=True, verbose_name='Tension dia.')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='Fréq. cardiaque')),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patients.patient')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
